---
deployment:
  tasks:
    - export PATH=/opt/cpanel/ea-nodejs18/bin/:$PATH
    - export FRONTEND_DEST=$HOME/public_html
    - export BACKEND_DEST=$HOME/backend
    - npm install
    - npm run build
    - /bin/cp -R dist/* $FRONTEND_DEST
    - /bin/mkdir -p $BACKEND_DEST
    - /bin/cp -R backend/* $BACKEND_DEST
